package indi.joynic.joodoo.security.keystore;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

/**
 * Keystore is file generated by keytool etc.
 *
 * @author Terrance Fung
 */
public class FileSystemKeyStoreFacade implements GeneralKeyStore {

    public static class Builder extends GeneralKeyStore.Builder {
        private String filePath;

        private File file;

        Builder filePath(String filePath) {
            this.filePath = filePath;

            return this;
        }

        /*@Override
        public BaseKeyStore build() {
            return new BaseKeyStore(this);
        }*/
    }
}