package indi.joynic.joodoo.security.keystore;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

/**
 * Keystore is file generated by keytool etc.
 *
 * @author Terrance Fung
 */
public class FileSystemKeyStoreFacade implements GeneralKeyStore {

    public static class Builder extends GeneralKeyStore.Builder {
        private String filePath;

        private File file;

        Builder filePath(String filePath) {
            this.filePath = filePath;

            return this;
        }

        Builder connect() {
            this.file = new File(filePath);
            return this;
        }

        Builder read() throws FileNotFoundException {
            FileInputStream fileInputStream = new FileInputStream(file);
            this.inputStream(fileInputStream);
            return this;
        }

        Builder write() throws FileNotFoundException {
            FileOutputStream fileOutputStream = new FileOutputStream(file);
            this.outputStream(fileOutputStream);
            return this;
        }
    }
}