package indi.joynic.joodoo.security.keystore;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

/**
 * Keystore is file generated by keytool etc.
 *
 * @author Terrance Fung
 */
public class FileSystemKeyStore implements GeneralKeyStore {

    public static class Builder extends GeneralKeyStore.Builder {
        GeneralKeyStore.Builder filePath(String filePath) throws FileNotFoundException {
            File file = new File(filePath);
            FileInputStream fileInputStream = new FileInputStream(file);
            this.inputStream(fileInputStream);

            return this;
        }

        @Override
        public BaseKeyStore build() {
            return new BaseKeyStore(this);
        }
    }
}